// <auto-generated />
namespace Mvc5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adding_new_model_large_image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_new_model_large_image));
        
        string IMigrationMetadata.Id
        {
            get { return "201605111540044_adding_new_model_large_image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
